# Generated by Django 2.1 on 2020-10-19 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='answers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('answer1', models.CharField(max_length=1000)),
                ('answer2', models.CharField(max_length=1000)),
                ('answer3', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=100)),
                ('lname', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('number', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=100)),
                ('jobtype', models.CharField(max_length=100)),
                ('sdate', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='markslist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('commentrate', models.FloatField(max_length=7)),
                ('resumematchper', models.FloatField(max_length=7)),
                ('botscore', models.FloatField(max_length=7)),
                ('avgtotal', models.FloatField(max_length=7)),
            ],
        ),
    ]
