# Generated by Django 2.1 on 2020-10-19 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='markslist',
            old_name='avgtotal',
            new_name='avg',
        ),
    ]
